baseURL = "https://victoriaashmanphotography.github.io/"
languageCode = "en-us"
title = "Victoria Ashman Photography"

SectionPagesMenu = "main"

[params]
  favicon = "favicon.png"
  site_logo = "/images/logo_white.png"
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/Victoria-Ashman-Photography-109436622481135"
  twitter = "https://twitter.com/vashmanimages"
  instagram = "https://www.instagram.com/victoriaashmanphotography"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/victoria-ashman-43738450"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-custom"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 4
  custom_css = ["css/custom.css"]
  body_classes = "avenir bg-near-white vap-body"
  post_content_classes = "vap-content"
  exclude_from_main_menu = ["featured"]
